/**
 * Mock data service for when database is not configured
 * Returns sample data to demonstrate the application
 */

export const mockDepartments = [
  {
    id: '1',
    name: 'Engineering',
    description: 'Software development and technical operations',
    budgetAllocated: 500000,
    managerId: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Sales',
    description: 'Sales and business development',
    budgetAllocated: 300000,
    managerId: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    name: 'Marketing',
    description: 'Marketing and brand management',
    budgetAllocated: 200000,
    managerId: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    name: 'Finance',
    description: 'Financial planning and accounting',
    budgetAllocated: 150000,
    managerId: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    name: 'Operations',
    description: 'Operations and logistics',
    budgetAllocated: 250000,
    managerId: null,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockEmployees = [
  {
    id: '1',
    firstName: 'John',
    lastName: 'Smith',
    email: 'john.smith@company.com',
    phoneNumber: '555-0101',
    jobTitle: 'Software Engineer',
    salary: 95000,
    hireDate: new Date('2022-01-15'),
    terminationDate: null,
    status: 'active',
    department: mockDepartments[0],
  },
  {
    id: '2',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@company.com',
    phoneNumber: '555-0102',
    jobTitle: 'Senior Software Engineer',
    salary: 125000,
    hireDate: new Date('2021-03-10'),
    terminationDate: null,
    status: 'active',
    department: mockDepartments[0],
  },
  {
    id: '3',
    firstName: 'Michael',
    lastName: 'Williams',
    email: 'michael.williams@company.com',
    phoneNumber: '555-0103',
    jobTitle: 'Sales Manager',
    salary: 85000,
    hireDate: new Date('2022-06-01'),
    terminationDate: null,
    status: 'active',
    department: mockDepartments[1],
  },
  {
    id: '4',
    firstName: 'Emily',
    lastName: 'Brown',
    email: 'emily.brown@company.com',
    phoneNumber: '555-0104',
    jobTitle: 'Marketing Specialist',
    salary: 65000,
    hireDate: new Date('2023-02-15'),
    terminationDate: null,
    status: 'active',
    department: mockDepartments[2],
  },
  {
    id: '5',
    firstName: 'David',
    lastName: 'Davis',
    email: 'david.davis@company.com',
    phoneNumber: '555-0105',
    jobTitle: 'Accountant',
    salary: 70000,
    hireDate: new Date('2022-09-01'),
    terminationDate: null,
    status: 'active',
    department: mockDepartments[3],
  },
  {
    id: '6',
    firstName: 'Jennifer',
    lastName: 'Miller',
    email: 'jennifer.miller@company.com',
    phoneNumber: '555-0106',
    jobTitle: 'Operations Manager',
    salary: 90000,
    hireDate: new Date('2021-11-15'),
    terminationDate: null,
    status: 'active',
    department: mockDepartments[4],
  },
  {
    id: '7',
    firstName: 'Robert',
    lastName: 'Wilson',
    email: 'robert.wilson@company.com',
    phoneNumber: '555-0107',
    jobTitle: 'DevOps Engineer',
    salary: 105000,
    hireDate: new Date('2022-04-20'),
    terminationDate: null,
    status: 'active',
    department: mockDepartments[0],
  },
  {
    id: '8',
    firstName: 'Lisa',
    lastName: 'Anderson',
    email: 'lisa.anderson@company.com',
    phoneNumber: '555-0108',
    jobTitle: 'Sales Representative',
    salary: 55000,
    hireDate: new Date('2023-01-10'),
    terminationDate: null,
    status: 'active',
    department: mockDepartments[1],
  },
];

export const mockPayrollRecords = [
  {
    id: '1',
    employee: mockEmployees[0],
    payPeriodStart: new Date('2024-01-01'),
    payPeriodEnd: new Date('2024-01-15'),
    grossPay: 3653.85,
    federalTax: 548.08,
    stateTax: 182.69,
    socialSecurityTax: 226.54,
    medicareTax: 52.98,
    deductions: 0,
    netPay: 2643.56,
    status: 'paid',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    employee: mockEmployees[1],
    payPeriodStart: new Date('2024-01-01'),
    payPeriodEnd: new Date('2024-01-15'),
    grossPay: 4807.69,
    federalTax: 721.15,
    stateTax: 240.38,
    socialSecurityTax: 298.08,
    medicareTax: 69.71,
    deductions: 0,
    netPay: 3478.37,
    status: 'paid',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    employee: mockEmployees[2],
    payPeriodStart: new Date('2024-01-01'),
    payPeriodEnd: new Date('2024-01-15'),
    grossPay: 3269.23,
    federalTax: 490.38,
    stateTax: 163.46,
    socialSecurityTax: 202.69,
    medicareTax: 47.40,
    deductions: 0,
    netPay: 2365.30,
    status: 'paid',
    createdAt: new Date('2024-01-15'),
  },
];

export const mockTransactions = [
  {
    id: '1',
    transactionDate: new Date('2024-01-15'),
    accountCode: '4000',
    accountName: 'Revenue',
    description: 'Product sales - January',
    debitAmount: 0,
    creditAmount: 50000,
    transactionType: 'sale',
    status: 'posted',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    transactionDate: new Date('2024-01-15'),
    accountCode: '1200',
    accountName: 'Accounts Receivable',
    description: 'Product sales - January',
    debitAmount: 50000,
    creditAmount: 0,
    transactionType: 'sale',
    status: 'posted',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    transactionDate: new Date('2024-01-20'),
    accountCode: '5000',
    accountName: 'Payroll Expense',
    description: 'Payroll - January 1-15',
    debitAmount: 30000,
    creditAmount: 0,
    transactionType: 'payroll',
    status: 'posted',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '4',
    transactionDate: new Date('2024-01-20'),
    accountCode: '2000',
    accountName: 'Cash',
    description: 'Payroll - January 1-15',
    debitAmount: 0,
    creditAmount: 30000,
    transactionType: 'payroll',
    status: 'posted',
    createdAt: new Date('2024-01-20'),
  },
];

export const mockBudgets = [
  {
    id: '1',
    fiscalYear: 2024,
    department: 'Engineering',
    category: 'salaries',
    allocatedAmount: 400000,
    spentAmount: 125000,
    committedAmount: 0,
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-12-31'),
    status: 'active',
  },
  {
    id: '2',
    fiscalYear: 2024,
    department: 'Sales',
    category: 'salaries',
    allocatedAmount: 200000,
    spentAmount: 50000,
    committedAmount: 0,
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-12-31'),
    status: 'active',
  },
  {
    id: '3',
    fiscalYear: 2024,
    department: 'Marketing',
    category: 'advertising',
    allocatedAmount: 150000,
    spentAmount: 35000,
    committedAmount: 20000,
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-12-31'),
    status: 'active',
  },
];

export const mockCustomers = [
  {
    id: '1',
    name: 'Acme Corporation',
    email: 'billing@acme.com',
    phone: '555-1001',
    address: '123 Business St',
    city: 'New York',
    state: 'NY',
    zipCode: '10001',
    country: 'USA',
    creditLimit: 100000,
    status: 'active',
  },
  {
    id: '2',
    name: 'TechStart Inc',
    email: 'accounts@techstart.com',
    phone: '555-1002',
    address: '456 Innovation Ave',
    city: 'San Francisco',
    state: 'CA',
    zipCode: '94102',
    country: 'USA',
    creditLimit: 75000,
    status: 'active',
  },
  {
    id: '3',
    name: 'Global Enterprises',
    email: 'finance@globalent.com',
    phone: '555-1003',
    address: '789 Commerce Blvd',
    city: 'Chicago',
    state: 'IL',
    zipCode: '60601',
    country: 'USA',
    creditLimit: 150000,
    status: 'active',
  },
];

export const mockInvoices = [
  {
    id: '1',
    invoiceNumber: 'INV-2024-001',
    customer: mockCustomers[0],
    invoiceDate: new Date('2024-01-10'),
    dueDate: new Date('2024-02-10'),
    subtotal: 25000,
    taxAmount: 2000,
    totalAmount: 27000,
    paidAmount: 27000,
    status: 'paid',
  },
  {
    id: '2',
    invoiceNumber: 'INV-2024-002',
    customer: mockCustomers[1],
    invoiceDate: new Date('2024-01-15'),
    dueDate: new Date('2024-02-15'),
    subtotal: 15000,
    taxAmount: 1200,
    totalAmount: 16200,
    paidAmount: 0,
    status: 'sent',
  },
  {
    id: '3',
    invoiceNumber: 'INV-2024-003',
    customer: mockCustomers[2],
    invoiceDate: new Date('2024-01-20'),
    dueDate: new Date('2024-02-20'),
    subtotal: 35000,
    taxAmount: 2800,
    totalAmount: 37800,
    paidAmount: 0,
    status: 'pending',
  },
];

export const mockVendors = [
  {
    id: '1',
    name: 'Office Supplies Co',
    vendorCode: 'VEND-001',
    contactPerson: 'Tom Anderson',
    email: 'sales@officesupplies.com',
    phone: '555-2001',
    paymentTerms: 'Net 30',
    status: 'active',
  },
  {
    id: '2',
    name: 'Tech Hardware Inc',
    vendorCode: 'VEND-002',
    contactPerson: 'Alice Chen',
    email: 'orders@techhardware.com',
    phone: '555-2002',
    paymentTerms: 'Net 45',
    status: 'active',
  },
  {
    id: '3',
    name: 'Furniture World',
    vendorCode: 'VEND-003',
    contactPerson: 'Bob Martinez',
    email: 'sales@furnitureworld.com',
    phone: '555-2003',
    paymentTerms: 'Net 60',
    status: 'active',
  },
];

export const mockPurchaseOrders = [
  {
    id: '1',
    poNumber: 'PO-2024-001',
    vendor: mockVendors[0],
    orderDate: new Date('2024-01-05'),
    expectedDeliveryDate: new Date('2024-01-20'),
    actualDeliveryDate: new Date('2024-01-18'),
    totalAmount: 5000,
    status: 'received',
  },
  {
    id: '2',
    poNumber: 'PO-2024-002',
    vendor: mockVendors[1],
    orderDate: new Date('2024-01-10'),
    expectedDeliveryDate: new Date('2024-01-25'),
    totalAmount: 15000,
    status: 'ordered',
  },
  {
    id: '3',
    poNumber: 'PO-2024-003',
    vendor: mockVendors[2],
    orderDate: new Date('2024-01-15'),
    expectedDeliveryDate: new Date('2024-02-01'),
    totalAmount: 8000,
    status: 'pending',
  },
];

export const mockInventoryItems = [
  {
    id: '1',
    sku: 'PROD-001',
    name: 'Widget Pro',
    description: 'Premium widget for professional use',
    category: 'Products',
    quantityOnHand: 150,
    quantityReserved: 25,
    quantityOnOrder: 0,
    reorderPoint: 50,
    reorderQuantity: 100,
    unitCost: 25.00,
    unitPrice: 45.00,
    warehouseLocation: 'A1-B2',
    status: 'active',
  },
  {
    id: '2',
    sku: 'PROD-002',
    name: 'Widget Basic',
    description: 'Standard widget for everyday use',
    category: 'Products',
    quantityOnHand: 45,
    quantityReserved: 10,
    quantityOnOrder: 100,
    reorderPoint: 50,
    reorderQuantity: 100,
    unitCost: 15.00,
    unitPrice: 25.00,
    warehouseLocation: 'A1-B3',
    status: 'active',
  },
  {
    id: '3',
    sku: 'SUPPLY-001',
    name: 'Office Supplies Bundle',
    description: 'Assorted office supplies',
    category: 'Supplies',
    quantityOnHand: 200,
    quantityReserved: 0,
    quantityOnOrder: 0,
    reorderPoint: 100,
    reorderQuantity: 200,
    unitCost: 10.00,
    unitPrice: 18.00,
    warehouseLocation: 'B2-C1',
    status: 'active',
  },
  {
    id: '4',
    sku: 'EQUIP-001',
    name: 'Computer Equipment',
    description: 'Various computer equipment',
    category: 'Equipment',
    quantityOnHand: 30,
    quantityReserved: 5,
    quantityOnOrder: 10,
    reorderPoint: 20,
    reorderQuantity: 25,
    unitCost: 500.00,
    unitPrice: 750.00,
    warehouseLocation: 'C1-D1',
    status: 'active',
  },
];

export const mockShipments = [
  {
    id: '1',
    trackingNumber: 'TRK-2024-001',
    orderId: 'ORD-001',
    orderType: 'outbound',
    carrier: 'FedEx',
    shipDate: new Date('2024-01-12'),
    estimatedDeliveryDate: new Date('2024-01-15'),
    actualDeliveryDate: new Date('2024-01-14'),
    shippingCost: 125.50,
    status: 'delivered',
  },
  {
    id: '2',
    trackingNumber: 'TRK-2024-002',
    orderId: 'ORD-002',
    orderType: 'outbound',
    carrier: 'UPS',
    shipDate: new Date('2024-01-18'),
    estimatedDeliveryDate: new Date('2024-01-22'),
    shippingCost: 185.00,
    status: 'in_transit',
  },
  {
    id: '3',
    trackingNumber: 'TRK-2024-003',
    orderId: 'PO-2024-002',
    orderType: 'inbound',
    carrier: 'DHL',
    shipDate: new Date('2024-01-22'),
    estimatedDeliveryDate: new Date('2024-01-25'),
    shippingCost: 95.00,
    status: 'pending',
  },
];

export const getMockStats = () => {
  return {
    hr: {
      activeEmployees: mockEmployees.filter(e => e.status === 'active').length,
      departments: mockDepartments.length,
      onLeave: 0,
    },
    payroll: {
      pending: 0,
      processed: 0,
      paid: mockPayrollRecords.filter(p => p.status === 'paid').length,
      totalPaid: mockPayrollRecords.reduce((sum, p) => sum + p.netPay, 0),
    },
    accounting: {
      totalTransactions: mockTransactions.length,
      totalDebits: mockTransactions.reduce((sum, t) => sum + t.debitAmount, 0),
      totalCredits: mockTransactions.reduce((sum, t) => sum + t.creditAmount, 0),
    },
    finance: {
      activeBudgets: mockBudgets.filter(b => b.status === 'active').length,
      totalRevenue: 50000,
      totalExpenses: 30000,
      netIncome: 20000,
    },
    billing: {
      totalCustomers: mockCustomers.length,
      pendingInvoices: mockInvoices.filter(i => i.status === 'pending').length,
      paidInvoices: mockInvoices.filter(i => i.status === 'paid').length,
      overdueInvoices: 0,
    },
    procurement: {
      totalVendors: mockVendors.length,
      pendingPOs: mockPurchaseOrders.filter(po => po.status === 'pending').length,
      orderedPOs: mockPurchaseOrders.filter(po => po.status === 'ordered').length,
      receivedPOs: mockPurchaseOrders.filter(po => po.status === 'received').length,
    },
    supplyChain: {
      pending: mockShipments.filter(s => s.status === 'pending').length,
      inTransit: mockShipments.filter(s => s.status === 'in_transit').length,
      delivered: mockShipments.filter(s => s.status === 'delivered').length,
      delayed: 0,
    },
    inventory: {
      totalItems: mockInventoryItems.length,
      totalValue: mockInventoryItems.reduce((sum, i) => sum + (i.quantityOnHand * i.unitCost), 0),
      lowStock: mockInventoryItems.filter(i => (i.quantityOnHand - i.quantityReserved) <= i.reorderPoint).length,
      onOrder: mockInventoryItems.reduce((sum, i) => sum + i.quantityOnOrder, 0),
    },
  };
};
